### ISSUE TITLE
Roon 1.7

### ISSUE THREAD

**Issue by Grant592** [florib779/Roon#1]
Hi florib,

I've had Roon working flawlessly using the 32-bit install process on Pop-os 19.10. Roon asked me to update to version 1.7 and now it won't open and I get this screen (see screenshot, the window on the right) before it closes itself. Do you have any suggestions about a fix? I've tried reinstalling both 64 and 32 bit versions but neither fix the issue
![Screenshot from 2019-11-22 09-40-49](https://user-images.githubusercontent.com/54353682/69415467-95126200-0d0c-11ea-9984-be19e4b573d5.png)

Kind regards

**Comment by axxelk** [comment]
had the same problem. Using the latest RoPieee/roon-on-wine install.sh and updating to the latest winetricks (https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks)  script made it work. The installation took quite some time.

**Comment by Grant592** [comment]
Thank you axxelk... Roon 1.7 now up and running!
